name: Build FRC Java with Gradle 2

on:
  - push

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: microsoft # Not sure which one to use
    - name: Build with Gradle
      run: |
        .\gradlew.bat build
