name: Google Java Formatter

on:
  - push

jobs:
  formatting:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: axel-op/googlejavaformat-action@v2.0.0
      with:
        args: "--skip-removing-unused-imports --replace"
